package workwork.test.andropediagits.domain.googbilling

enum class PayState {
    COURSEBUYADVANCED,
    COURSEBUYINDEPTH,
    THEMEBUYCALCUL,
    THEMEBUYNEWSLIST,
    THEMEBUYNOTES,
    ONEANDROPOINTBUY,
    TENANDROPOINTBUY,
    FIFTYANDROPOINTBUY,
    HUNDREDANDROPOINTBUY,
    FIVEHUNDREDANDROPOINTBUY,
    THOUSANDANDROPOINTBUY,
    PREMIUMONEMOUNTHBUY,
    PREMIUMSIXMOUNTHBUY,
    PREMIUMYEARBUY
}