package workwork.test.andropediagits.domain.useCases.userLogic.state

enum class SoundState {
    THEMEOPENSOUND,
    THEMETERMCLOSE,
    INTERACTIVETOUCHSOUND,
    INTERACTIVENEXTSOUND,
    VICTROINETOUCHSOUND,
    VICTORINENEXTSOUND,
   TERMNOTEND,
    COURSEBUYSOUND,
    STRIKEMODESOUND
}